version: '2'

services:

  letsencrypt:
    image: cybergatelabs/letsencrypt
    restart: unless-stopped
    container_name: letsencrypt
    hostname: letsencrypt
    ports:
      - 80:80
      - 443:443
    cap_add:
      - NET_ADMIN
    volumes:
      - ./data/letsencrypt/config:/config
    env_file: 
      - ./.letsencrypt.env

  osticket:
    image: campbellsoftwaresolutions/osticket
    container_name: osticket
    #hostname: osticket
    env_file: 
      - ./.osticket.env
    volumes:
      - ./data/osticket/plugins:/data/upload/include/plugins
      - ./data/osticket/nginx/log:/var/log/nginx
    links:
      - mysql_db:mysql
    #ports:
    #  - "5335:80"
    restart: always

  mysql:
    image: mysql:5
    container_name: mysql_db
    #hostname: mysql
    env_file:
      - ./.mariadb.env
    volumes:
     - mariadb-data:/var/lib/mysql
    restart: always
 
volumes:
  osticket-data:
  mariadb-data:

 
    
