version: '2'

services:

  letsencrypt:
    image: cybergatelabs/letsencrypt
    restart: unless-stopped
    container_name: letsencrypt
    hostname: letsencrypt
    ports:
      - 80:80
      - 443:443
    cap_add:
      - NET_ADMIN
    volumes:
      - ./data/letsencrypt/config:/config
    env_file: 
      - ./.letsencrypt.env

  osticket:
    image: osticket/osticket
    container_name: osticket
    hostname: osticket
    env_file: 
      - ./.osticket.env
    links:
      - mysql:mysql
    ports:
      - "5335:80"
    restart: always

  mysql:
    image: mariadb
    container_name: osticket
    hostname: osticket
    env_file:
      -./.mariadb.env
    restart: always
 
 volumes:
  osticket-data:
  mariadb-data:

 
    
